### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ginolhac** [ginolhac/upnews#3]
- [x] visualize NEWS without selecting
- [x] news as icon like the CRAN widget
- [x] update button text "install x packages" to "update x packages"
- [x] allow refresh once install done
- [x] fix warning when table is first loaded
- [x] don't create links on a empty table
- [x] do some caching to speed up refresh manual or after upgrades
- [x] for NEWS.md propose a knit and display in Viewer
- [ ] tryCatch `Warning: Error in curl::curl_fetch_memory: Timeout was reached: Resolving timed out after 10000 milliseconds`
- [x] tooltips from bootstrap, @pvictor 
- [ ] css loader while pkgs are upgraded
- [ ] follow symbolic link (see `r-lib/gh`, NEWS.md -> inst/NEWS.md)
